# Generated by Django 3.2.21 on 2023-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tel',
            name='FIO',
            field=models.CharField(max_length=200),
        ),
    ]
